### ISSUE TITLE
Solution branch does not reproject the dataset

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-pca-numpy-lab#1]
The final step has 
```
eigenvectors_sorted[:2]
```

the correct is (I believe):

```
transformed = eigenvectors_sorted[:2].dot(data.T).T
transformed
```

**Comment by jessepisel** [comment]
The solution proposed above is correct. I have updated the solution branch with commit 877ba4b988791452c81d6f352b7e3fd70d606ba3 .

I am closing this issue at this time.
